<?php

namespace models;

/**
 * Project : srv_www_IrisWB
 * Created for IRIS-PHP 1.0 RC2
 *
 * Entity class for Clients generated by 
 * iris.php -- entitygenerate
 */
class TClients extends \Iris\DB\_Entity {
    
}


