<?php

namespace models;

/**
 * Project : srv_IrisWB
 * Created for IRIS-PHP 1.0 RC2
 *
 * Entity class for Demo generated by 
 * iris.php -- entitygenerate
 */
class TDemo extends \Iris\DB\_Entity {
    
}


