<?php

namespace modules\db\controllers;

/**
 * A controller with CRUD capabilities generated by 
 * iris.php -- entitygenerate
 * 
 */
class customers extends _db {
use \Iris\DB\DataBrowser\tCrudManager;
    
    public function _init() {
        // A proposal for the title
        $this->__Title = "Customers manager"; 
    }
    
    public function showAction() {
        $icons = \models\crud\CrudIconManager::getInstance();
        $icons
                // controller serving as a manager
                ->setController('/db/customers')
                // action name end (for instance insert_XXXX)
                ->setActionName('Customers')
                // gender and entity name for tooltip (example M'_employee: masculine and special article 'an')
                ->setEntity("M_client")
                // field containing a significative description 
                ->setDescField('Name')
                // primary key field
                ->setIdField('id');
        // Get all the data in Customers
        $EM = \models\_dbManager::GetEM();
        $tEntity = \models\TCustomers::GetEntity($EM);
        $this->__customers = $tEntity->fetchAll();
    }

}
