<?php

namespace modules\db\controllers;

/**
 * A controller with CRUD capabilities generated by 
 * iris.php -- entitygenerate
 * 
 */
class democ extends _db {
use \Iris\DB\DataBrowser\tCrudManager;
    
    public function _init() {
        // A proposal for the title
        $this->__Title = "Demo manager"; 
    }
    
    public function indexAction() {
        $icons = \models\crud\CrudIconManager::getInstance();
        $icons
                // controller serving as a manager
                ->setController('/db/democ')
                // action name end (for instance insert_XXXX)
                ->setActionName('demo')
                // gender and entity name for tooltip (example M'_employee: masculine and special article 'an')
                ->setEntity("F_description")
                // field containing a significative description 
                ->setDescField('Description')
                // primary key field
                ->setIdField('id');
        // Get all the data in Demo
        $tEntity = \models\TDemo::GetEntity();
        $this->__lines = $tEntity->fetchAll();
    }

}
