<?php

namespace modules\db\controllers;

/**
 * A controller with CRUD capabilities generated by 
 * iris.php -- entitygenerate
 * 
 */
class products extends _db {
use \Iris\DB\DataBrowser\tCrudManager;
    
    public function _init() {
        // A proposal for the title
        $this->__Title = "Products manager"; 
    }
    
    public function showAction() {
        $icons = \models\crud\CrudIconManager::getInstance();
        $icons
                // controller serving as a manager
                ->setController('/db/products')
                // action name end (for instance insert_XXXX)
                ->setActionName('Products')
                // gender and entity name for tooltip (example M'_employee: masculine and special article 'an')
                ->setEntity("M_product")
                // field containing a significative description 
                ->setDescField('Name')
                // primary key field
                ->setIdField('id');
        // Get all the data in Products
        $tEntity = \models\TProducts::GetEntity();
        $this->__products = $tEntity->fetchAll();
    }

}
