<?php
namespace modules\db\controllers;

/*
 * This file is part of IRIS-PHP, distributed under the General Public License version 3.
 * A copy of the GNU General Public Version 3 is readable in /library/gpl-3.0.txt.
 * More details about the copyright may be found at
 * <http://irisphp.org/copyright> or <http://www.gnu.org/licenses/>
 *  
 * @copyright 2011-2017 Jacques THOORENS
 */

/**
 * A controller with CRUD capabilities generated by 
 * iris.php -- entitygenerate
 * 
 */
class products extends _db {
use \Iris\DB\DataBrowser\tCrudManager;
    
    public function _init() {
        // A proposal for the title
        $this->__Title = "Products manager"; 
    }
    
    public function manageAction() {
        $icons = \models\crud\CrudIconManager::getInstance();
        $icons
                // controller serving as a manager
                ->setController('/db/products')
                // action name end (for instance insert_XXXX)
                ->setActionName('Products')
                // gender and entity name for tooltip (example M'_employee: masculine and special article 'an')
                ->setEntity("M_product")
                // field containing a significative description 
                ->setDescField('Name')
                // primary key field
                ->setIdField('id')
                ->forceLanguage('english');;
        // Get all the data in Products
        
        /*$icons = $this->crudIcon();
    $icons
        ->setController('/db/customers')
        ->setActionName('customer')
        ->setEntity($this->_("N_customer"))
        ->setDescField('Name')
        ->setIdField('id')
        ->setDefaultIconDir('/images/icones')
        ->forceLanguage('english');*/
        $EM = \models\TProducts::GetEM();
        $tEntity = \models\TProducts::GetEntity($EM);
        $this->__products = $tEntity->fetchAll();
    }

}
