<?php

namespace modules\db\controllers;

/**
 * A controller with CRUD capabilities generated by 
 * iris.php -- entitygenerate
 * 
 */
class products extends _db {
use \Iris\DB\DataBrowser\tCrudManager;
    
    public function _init() {
        // A proposal for the title
        $this->__Title = "Products manager"; 
    }
    
    public function showAction() {
        $icons = \models\crud\CrudIconManager::getInstance();
        $icons
                // controller serving as a manager
                ->setController('/db/products')
                // action name end (for instance insert_XXXX)
                ->setActionName('Products')
                // gender and entity name for tooltip (example M'_employee: masculine and special article 'an')
                ->setEntity("M_product")
                // field containing a significative description 
                ->setDescField('Name')
                // primary key field
                ->setIdField('id')
                ->forceLanguage('english');;
        // Get all the data in Products
        
        /*$icons = $this->crudIcon();
    $icons
        ->setController('/db/customers')
        ->setActionName('customer')
        ->setEntity($this->_("N_customer"))
        ->setDescField('Name')
        ->setIdField('id')
        ->setDefaultIconDir('/images/icones')
        ->forceLanguage('english');*/
        $EM = \models\_dbManager::GetEM();
        $tEntity = \models\TProducts::GetEntity($EM);
        $this->__products = $tEntity->fetchAll();
    }

}
