<?php

namespace modules\db2\controllers;

/**
 * A controller with CRUD capabilities generated by 
 * iris.php -- entitygenerate
 * 
 */
class clients extends _db2 {
use \Iris\DB\DataBrowser\tCrudManager;
    
    public function _init() {
        // A proposal for the title
        $this->__Title = "Clients manager"; 
    }
    
    public function indexAction() {
        $icons = \models\crud\CrudIconManager::getInstance();
        $icons
                // controller serving as a manager
                ->setController('/db2/clients')
                // action name end (for instance insert_XXXX)
                ->setActionName('Clients')
                // gender and entity name for tooltip (example M'_employee: masculine and special article 'an')
                ->setEntity("M_Nom du client")
                // field containing a significative description 
                ->setDescField('Name')
                // primary key field
                ->setIdField('id');
        // Get all the data in Clients
        $EM = \models\TCustomers::GetEM();
        $tEntity = \models\TCustomers::GetEntity($EM);
        $this->__lines = $tEntity->fetchAll();
    }

}
