<?php

namespace models\crud;


/**
 * Project : srv_www_IrisWB
 * Created for IRIS-PHP 1.0 RC2
 *
 * CRUD operations for Clients generated by 
 * iris.php -- entitygenerate
 */
class Clients extends \Iris\DB\DataBrowser\_Crud {
    
    
    
    
    public function __construct($param = NULL) {
        $this->setCrudEntity('Clients');
        static::$_EntityManager = \models\TInvoices::GetEM();'...';
        parent::__construct($param);
        // where to go after CRUD
        $this->setEndUrl('index');
        // where to in case of error
        $this->setErrorURL('error');
    }


    
}
