<?php
// VERSION MARS
namespace models\crud;


/**
 * Project : srv_IrisWB
 * Created for IRIS-PHP 1.0 RC2
 *
 * CRUD operations for Customers generated by 
 * iris.php -- entitygenerate
 */
class Customers extends _localCrud {
    
    
    
    
    public function __construct($param = NULL) {
        static::$_EntityManager = \models\TInvoices::GetEM();
        parent::__construct($param);
        // where to go after CRUD
        $this->setEndUrl('show');
        // where to in case of error
        $this->setErrorURL('error');
    }


    
}
