<?php

namespace models\crud;


/**
 * Project : srv_IrisWB
 * Created for IRIS-PHP 1.0 RC2
 *
 * CRUD operations for Users generated by 
 * iris.php -- entitygenerate
 */
class Users_____ extends \Iris\Users\Login {

    // As in mother class
    // protected static $_IdField = 'id';

    /**
     *The field containing the username: different from
     * the mother class (by purpose as a demo)
     * 
     * @var string
     */
    protected static $_NameField = 'Name';

    // As in mother class
    //protected static $_RoleField = "Role";
    // As in mother class
    //protected static $_PasswordField = 'Password';
    // As in mother class
    //protected static $_EmailField = "Email";

    
    public function __construct($param = \NULL) {
      
        parent::__construct($param);
        $entity = \models\TUsers::GetEntity();
        $this->setEntity($entity);
        $this->setErrorURL(\NULL);
        $this->setEndURL("/acl/login/index");
        $this->setContinuationURL('/main');
        
    }

    protected function _postLogin($object, $username) {
        
    }

}
