<?php

namespace modules\acl\controllers;

/**
 * A controller with CRUD capabilities generated by 
 * iris.php -- entitygenerate
 * 
 */
class temp extends _acl {
use \Iris\DB\DataBrowser\tCrudManager;
    
    public function _init() {
        // A proposal for the title
        $this->__Title = "Users manager"; 
    }
    
    public function indexAction() {
        $icons = \models\crud\CrudIconManager::getInstance();
        $icons
                // controller serving as a manager
                ->setController('/acl/temp')
                // action name end (for instance insert_XXXX)
                ->setActionName('Users')
                // gender and entity name for tooltip (example M'_employee: masculine and special article 'an')
                ->setEntity("M_user")
                // field containing a significative description 
                ->setDescField('Name')
                // primary key field
                ->setIdField('id');
        // Get all the data in Users
        $tEntity = \models\TUsers::GetEntity();
        $this->__lines = $tEntity->fetchAll();
    }

}
