{PHP_TAG}

namespace models\crud;


/**
 * {PROJECTNAME}
 * Created for IRIS-PHP {IRISVERSION}
 *
 * CRUD operations for {ENTITY} generated by 
 * iris.php -- entitygenerate
 */
class {ENTITY} extends \Iris\DB\DataBrowser\_Crud {
    
    {GETEMDEF}
    
    
    public function __construct($param = NULL) {
        parent::__construct($param);
        $entity = \Iris\DB\TableEntity::GetEntity('{ENTITY}'{GETEMCALL});
        $this->setEntity($entity);
        // where to go after CRUD
        $this->setEndUrl('index');
        // where to in case of error
        $this->setErrorURL('error');
    }


    
}
