{PHP_TAG}

namespace models;

/**
 * {PROJECTNAME}
 * Created for IRIS-PHP {IRISVERSION}
 *
 * Entity class for {ENTITY} generated by 
 * iris.php -- entitygenerate
 */
class T{ENTITY} extends \Iris\DB\_Entity {
    {EXTERNALEM}
}


